include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    prefer_single_quotes: error
    invalid_annotation_target: ignore
linter:
  rules:
    avoid_print: false
    prefer_single_quotes: true
