include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    missing_required_param: warning
    missing_return: warning
    invalid_annotation_target: ignore

  plugins:
    - dart_code_metrics

  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.graphql.dart"
    - "**/*.graphql.g.dart"
    - "**/initializer.config.dart"
    - "**/generated"
    - "**/*.gr.dart"
    - "**/*.al.dart"
    - "**/*.i18n.dart"

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 50
  metrics-exclude:
    - test/**
  rules:
    #! - avoid-ignoring-return-values
    #  - avoid-late-keyword
    - avoid-missing-enum-constant-in-map
    - avoid-nested-conditional-expressions
    #!- avoid-non-null-assertion
    - avoid-throw-in-catch-block
    - avoid-unnecessary-type-casts
    - avoid-unused-parameters
    - avoid-unnecessary-type-assertions
    - binary-expression-operand-order
    - double-literal-format
    #  - member-ordering
    #  - member-ordering-extended
    #  - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    #  - no-equal-arguments
    - no-equal-then-else
    #  - no-magic-number
    - no-object-declaration
    #  - prefer-conditional-expressions
    #  - prefer-correct-identifier-length
    - prefer-correct-type-name
    - prefer-first
    - prefer-last
    #!- prefer-match-file-name
    - prefer-trailing-comma
    - always-remove-listener
    - avoid-returning-widgets
    - avoid-unnecessary-setstate
    #!- avoid-wrapping-in-padding
    - prefer-const-border-radius
    # - prefer-extracting-callbacks
    #!- prefer-single-widget-per-file
    - prefer-intl-name
    - provide-correct-intl-args
